#!/bin/bash

server="49.12.1.242"
op_port=(4000 4321 8082 22 80)
cl_port=(3306)
op_len=${#op_port[@]}
cl_len=${#cl_port[@]}

echo "Checking for opened ports:"

for (( x=0; x<$op_len; x++ )); do
        nc -zvn $server ${op_port[x]} &> /dev/null
        result=$?
        0 &> /dev/null
        if [ "$result" != 0 ]; then
                echo "${op_port[x]}" is closed on $server - Failed
        else
                echo "${op_port[x]}" is open on $server - Successful
        fi
        done

echo "Checking for closed ports:"

for (( x=0; x<$cl_len; x++ )); do
        nc -zvn $server ${cl_port[x]} &> /dev/null
        result=$?
        0 &> /dev/null
        if [ "$result" != 0 ]; then
                echo "${cl_port[x]}" is closed on $server - Succesful
        else
                echo "${cl_port[x]}" is open on $server - Failed
        fi
        done

exit
