#!/bin/bash
#for TLS\TBS works
iptables -t filter -A INPUT -i lo -j ACCEPT
iptables -t filter -A OUTPUT -o lo -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 65000:65050 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 65000:65050 -j ACCEPT
# port 3306 must be closed for external connection
iptables -t filter -A INPUT -p tcp --dport 3306 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 3306 -j DROP
iptables -t filter -A INPUT -p tcp --dport 4000 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 4321 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 8082 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT

#for TLS and TBS interconnection, Arbitrator

iptables -t filter -A INPUT -p tcp --dport 4567 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 4567 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 4568 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 4444 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 13000 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 27017 -j ACCEPT
